window.PANSUB_GLOSSARY = {
  version: '2026.05.26',
  terms: [
    { terms: ['academic literature', 'scholarly literature'], zhCN: '学术文献', zhTW: '學術文獻' },
    { terms: ['research question', 'research questions'], zhCN: '研究问题', zhTW: '研究問題' },
    { terms: ['hypothesis', 'hypotheses'], zhCN: '假设', zhTW: '假設' },
    { terms: ['methodology', 'research methodology'], zhCN: '研究方法论', zhTW: '研究方法論' },
    { terms: ['qualitative research'], zhCN: '定性研究', zhTW: '質性研究' },
    { terms: ['quantitative research'], zhCN: '定量研究', zhTW: '量化研究' },
    { terms: ['case study', 'case studies'], zhCN: '案例研究', zhTW: '個案研究' },
    { terms: ['literature review'], zhCN: '文献综述', zhTW: '文獻綜述' },
    { terms: ['peer review'], zhCN: '同行评审', zhTW: '同儕審查' },
    { terms: ['citation', 'citations'], zhCN: '引用', zhTW: '引用' },
    { terms: ['theoretical framework'], zhCN: '理论框架', zhTW: '理論框架' },
    { terms: ['conceptual framework'], zhCN: '概念框架', zhTW: '概念框架' },
    { terms: ['independent variable', 'independent variables'], zhCN: '自变量', zhTW: '自變量' },
    { terms: ['dependent variable', 'dependent variables'], zhCN: '因变量', zhTW: '因變量' },
    { terms: ['control variable', 'control variables'], zhCN: '控制变量', zhTW: '控制變量' },
    { terms: ['sample size'], zhCN: '样本量', zhTW: '樣本數' },
    { terms: ['confidence interval', 'confidence intervals'], zhCN: '置信区间', zhTW: '信賴區間' },
    { terms: ['standard deviation'], zhCN: '标准差', zhTW: '標準差' },
    { terms: ['statistical significance'], zhCN: '统计显著性', zhTW: '統計顯著性' },
    { terms: ['p-value', 'p value'], zhCN: 'p 值', zhTW: 'p 值' },
    { terms: ['regression analysis'], zhCN: '回归分析', zhTW: '迴歸分析' },
    { terms: ['correlation coefficient'], zhCN: '相关系数', zhTW: '相關係數' },
    { terms: ['normal distribution'], zhCN: '正态分布', zhTW: '常態分布' },
    { terms: ['null hypothesis'], zhCN: '零假设', zhTW: '虛無假設' },
    { terms: ['alternative hypothesis'], zhCN: '备择假设', zhTW: '對立假設' },

    { terms: ['algorithm', 'algorithms'], zhCN: '算法', zhTW: '演算法' },
    { terms: ['data structure', 'data structures'], zhCN: '数据结构', zhTW: '資料結構' },
    { terms: ['object oriented programming', 'object-oriented programming'], zhCN: '面向对象编程', zhTW: '物件導向程式設計' },
    { terms: ['application programming interface', 'api', 'apis'], zhCN: '应用程序接口', zhTW: '應用程式介面' },
    { terms: ['frontend', 'front end', 'front-end'], zhCN: '前端', zhTW: '前端' },
    { terms: ['backend', 'back end', 'back-end'], zhCN: '后端', zhTW: '後端' },
    { terms: ['runtime'], zhCN: '运行时', zhTW: '執行階段' },
    { terms: ['asynchronous'], zhCN: '异步', zhTW: '非同步' },
    { terms: ['synchronous'], zhCN: '同步', zhTW: '同步' },
    { terms: ['callback function', 'callback functions'], zhCN: '回调函数', zhTW: '回呼函式' },
    { terms: ['promise', 'promises'], zhCN: 'Promise 对象', zhTW: 'Promise 物件' },
    { terms: ['event loop'], zhCN: '事件循环', zhTW: '事件迴圈' },
    { terms: ['dom', 'document object model'], zhCN: '文档对象模型', zhTW: '文件物件模型' },
    { terms: ['database', 'databases'], zhCN: '数据库', zhTW: '資料庫' },
    { terms: ['relational database', 'relational databases'], zhCN: '关系数据库', zhTW: '關聯式資料庫' },
    { terms: ['database schema', 'relational schema'], zhCN: '数据库模式', zhTW: '資料庫綱要' },
    { terms: ['primary key', 'primary keys'], zhCN: '主键', zhTW: '主鍵' },
    { terms: ['foreign key', 'foreign keys'], zhCN: '外键', zhTW: '外鍵' },
    { terms: ['candidate key', 'candidate keys'], zhCN: '候选键', zhTW: '候選鍵' },
    { terms: ['composite key', 'composite keys'], zhCN: '复合键', zhTW: '複合鍵' },
    { terms: ['cardinality'], zhCN: '基数', zhTW: '基數' },
    { terms: ['one-to-one relationship'], zhCN: '一对一关系', zhTW: '一對一關係' },
    { terms: ['one-to-many relationship'], zhCN: '一对多关系', zhTW: '一對多關係' },
    { terms: ['many-to-many relationship'], zhCN: '多对多关系', zhTW: '多對多關係' },
    { terms: ['entity relationship diagram', 'er diagram', 'erd'], zhCN: '实体关系图', zhTW: '實體關係圖' },
    { terms: ['normalization'], zhCN: '规范化', zhTW: '正規化' },
    { terms: ['first normal form'], zhCN: '第一范式', zhTW: '第一正規化' },
    { terms: ['second normal form'], zhCN: '第二范式', zhTW: '第二正規化' },
    { terms: ['third normal form'], zhCN: '第三范式', zhTW: '第三正規化' },
    { terms: ['sql query', 'sql queries'], zhCN: 'SQL 查询', zhTW: 'SQL 查詢' },

    { terms: ['business model', 'business models'], zhCN: '商业模式', zhTW: '商業模式' },
    { terms: ['value proposition', 'value propositions'], zhCN: '价值主张', zhTW: '價值主張' },
    { terms: ['stakeholder', 'stakeholders'], zhCN: '利益相关者', zhTW: '利害關係人' },
    { terms: ['competitive advantage'], zhCN: '竞争优势', zhTW: '競爭優勢' },
    { terms: ['market segmentation'], zhCN: '市场细分', zhTW: '市場區隔' },
    { terms: ['target market', 'target markets'], zhCN: '目标市场', zhTW: '目標市場' },
    { terms: ['brand equity'], zhCN: '品牌资产', zhTW: '品牌權益' },
    { terms: ['customer journey'], zhCN: '客户旅程', zhTW: '顧客旅程' },
    { terms: ['conversion rate'], zhCN: '转化率', zhTW: '轉換率' },
    { terms: ['key performance indicator', 'key performance indicators', 'kpi', 'kpis'], zhCN: '关键绩效指标', zhTW: '關鍵績效指標' },
    { terms: ['supply chain', 'supply chains'], zhCN: '供应链', zhTW: '供應鏈' },
    { terms: ['inventory management'], zhCN: '库存管理', zhTW: '庫存管理' },
    { terms: ['economies of scale'], zhCN: '规模经济', zhTW: '規模經濟' },
    { terms: ['opportunity cost', 'opportunity costs'], zhCN: '机会成本', zhTW: '機會成本' },
    { terms: ['marginal cost', 'marginal costs'], zhCN: '边际成本', zhTW: '邊際成本' },
    { terms: ['marginal revenue'], zhCN: '边际收益', zhTW: '邊際收益' },
    { terms: ['price elasticity of demand'], zhCN: '需求价格弹性', zhTW: '需求價格彈性' },
    { terms: ['gross domestic product', 'gdp'], zhCN: '国内生产总值', zhTW: '國內生產總值' },
    { terms: ['inflation rate'], zhCN: '通货膨胀率', zhTW: '通貨膨脹率' },
    { terms: ['interest rate', 'interest rates'], zhCN: '利率', zhTW: '利率' },
    { terms: ['monetary policy'], zhCN: '货币政策', zhTW: '貨幣政策' },
    { terms: ['fiscal policy'], zhCN: '财政政策', zhTW: '財政政策' },
    { terms: ['balance sheet'], zhCN: '资产负债表', zhTW: '資產負債表' },
    { terms: ['income statement'], zhCN: '利润表', zhTW: '損益表' },
    { terms: ['cash flow statement'], zhCN: '现金流量表', zhTW: '現金流量表' },
    { terms: ['accounts receivable'], zhCN: '应收账款', zhTW: '應收帳款' },
    { terms: ['accounts payable'], zhCN: '应付账款', zhTW: '應付帳款' },
    { terms: ['depreciation'], zhCN: '折旧', zhTW: '折舊' },
    { terms: ['amortization'], zhCN: '摊销', zhTW: '攤銷' },
    { terms: ['net present value', 'npv'], zhCN: '净现值', zhTW: '淨現值' },
    { terms: ['internal rate of return', 'irr'], zhCN: '内部收益率', zhTW: '內部報酬率' },
    { terms: ['capital expenditure', 'capex'], zhCN: '资本支出', zhTW: '資本支出' },
    { terms: ['operating expenditure', 'opex'], zhCN: '运营支出', zhTW: '營運支出' },

    { terms: ['visual culture'], zhCN: '视觉文化', zhTW: '視覺文化' },
    { terms: ['art history'], zhCN: '艺术史', zhTW: '藝術史' },
    { terms: ['contemporary art'], zhCN: '当代艺术', zhTW: '當代藝術' },
    { terms: ['modernism'], zhCN: '现代主义', zhTW: '現代主義' },
    { terms: ['postmodernism'], zhCN: '后现代主义', zhTW: '後現代主義' },
    { terms: ['aesthetic', 'aesthetics'], zhCN: '美学', zhTW: '美學' },
    { terms: ['composition'], zhCN: '构图', zhTW: '構圖' },
    { terms: ['perspective'], zhCN: '透视', zhTW: '透視' },
    { terms: ['medium', 'media'], zhCN: '媒介', zhTW: '媒介' },
    { terms: ['installation art'], zhCN: '装置艺术', zhTW: '裝置藝術' },
    { terms: ['performance art'], zhCN: '行为艺术', zhTW: '行為藝術' },
    { terms: ['curatorial practice'], zhCN: '策展实践', zhTW: '策展實踐' },
    { terms: ['semiotics'], zhCN: '符号学', zhTW: '符號學' },
    { terms: ['iconography'], zhCN: '图像志', zhTW: '圖像學' },
    { terms: ['typography'], zhCN: '字体排印', zhTW: '字體排印' },
    { terms: ['user experience', 'ux'], zhCN: '用户体验', zhTW: '使用者體驗' },
    { terms: ['user interface', 'ui'], zhCN: '用户界面', zhTW: '使用者介面' },
    { terms: ['design thinking'], zhCN: '设计思维', zhTW: '設計思維' },
    { terms: ['brand identity'], zhCN: '品牌识别', zhTW: '品牌識別' },
    { terms: ['narrative structure'], zhCN: '叙事结构', zhTW: '敘事結構' },

    { terms: ['cognitive psychology'], zhCN: '认知心理学', zhTW: '認知心理學' },
    { terms: ['social psychology'], zhCN: '社会心理学', zhTW: '社會心理學' },
    { terms: ['working memory'], zhCN: '工作记忆', zhTW: '工作記憶' },
    { terms: ['long-term memory'], zhCN: '长期记忆', zhTW: '長期記憶' },
    { terms: ['social construct', 'social constructs'], zhCN: '社会建构', zhTW: '社會建構' },
    { terms: ['cultural capital'], zhCN: '文化资本', zhTW: '文化資本' },
    { terms: ['social stratification'], zhCN: '社会分层', zhTW: '社會分層' },
    { terms: ['public policy'], zhCN: '公共政策', zhTW: '公共政策' },
    { terms: ['policy analysis'], zhCN: '政策分析', zhTW: '政策分析' },
    { terms: ['constitutional law'], zhCN: '宪法', zhTW: '憲法' },
    { terms: ['contract law'], zhCN: '合同法', zhTW: '契約法' },
    { terms: ['tort law'], zhCN: '侵权法', zhTW: '侵權法' },
    { terms: ['case law'], zhCN: '判例法', zhTW: '判例法' },
    { terms: ['legal precedent', 'precedent'], zhCN: '法律先例', zhTW: '法律先例' },
    { terms: ['burden of proof'], zhCN: '举证责任', zhTW: '舉證責任' },
    { terms: ['due process'], zhCN: '正当程序', zhTW: '正當程序' },

    { terms: ['learning outcome', 'learning outcomes'], zhCN: '学习成果', zhTW: '學習成果' },
    { terms: ['formative assessment'], zhCN: '形成性评价', zhTW: '形成性評量' },
    { terms: ['summative assessment'], zhCN: '总结性评价', zhTW: '總結性評量' },
    { terms: ['rubric', 'rubrics'], zhCN: '评分量规', zhTW: '評分規準' },
    { terms: ['curriculum design'], zhCN: '课程设计', zhTW: '課程設計' },
    { terms: ['pedagogy'], zhCN: '教学法', zhTW: '教學法' },
    { terms: ['scaffolding'], zhCN: '支架式教学', zhTW: '鷹架式教學' },
    { terms: ['constructive alignment'], zhCN: '建构性一致', zhTW: '建構性對齊' },

    { terms: ['cell membrane'], zhCN: '细胞膜', zhTW: '細胞膜' },
    { terms: ['gene expression'], zhCN: '基因表达', zhTW: '基因表現' },
    { terms: ['protein synthesis'], zhCN: '蛋白质合成', zhTW: '蛋白質合成' },
    { terms: ['immune system'], zhCN: '免疫系统', zhTW: '免疫系統' },
    { terms: ['clinical trial', 'clinical trials'], zhCN: '临床试验', zhTW: '臨床試驗' },
    { terms: ['randomized controlled trial', 'randomised controlled trial', 'rct'], zhCN: '随机对照试验', zhTW: '隨機對照試驗' },
    { terms: ['evidence based practice', 'evidence-based practice'], zhCN: '循证实践', zhTW: '實證實務' },
    { terms: ['public health'], zhCN: '公共卫生', zhTW: '公共衛生' },
    { terms: ['epidemiology'], zhCN: '流行病学', zhTW: '流行病學' },
    { terms: ['prevalence'], zhCN: '患病率', zhTW: '盛行率' },
    { terms: ['incidence'], zhCN: '发病率', zhTW: '發生率' },

    { terms: ['free body diagram'], zhCN: '受力图', zhTW: '受力圖' },
    { terms: ['equilibrium'], zhCN: '平衡', zhTW: '平衡' },
    { terms: ['momentum'], zhCN: '动量', zhTW: '動量' },
    { terms: ['thermodynamics'], zhCN: '热力学', zhTW: '熱力學' },
    { terms: ['fluid mechanics'], zhCN: '流体力学', zhTW: '流體力學' },
    { terms: ['finite element analysis', 'fea'], zhCN: '有限元分析', zhTW: '有限元素分析' },
    { terms: ['sustainable development'], zhCN: '可持续发展', zhTW: '永續發展' },
    { terms: ['carbon footprint'], zhCN: '碳足迹', zhTW: '碳足跡' },
    { terms: ['life cycle assessment'], zhCN: '生命周期评估', zhTW: '生命週期評估' }
  ]
};
